{{- if .Values.oidcSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: oidc-auth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- with .Values.oidcSecret }}
  clientID: {{ .clientID | required "oidcSecret.clientID must be set" | b64enc | quote }}
  clientSecret: {{ .clientSecret | required "oidcSecret.clientSecret must be set" | b64enc | quote }}
  issuerURL: {{ .issuerURL | required "oidcSecret.issuerURL must be set" | b64enc | quote }}
  redirectURL: {{ .redirectURL | required "oidcSecret.redirectURL must be set" | b64enc | quote }}
  {{- if .claimUsername }}
  claimUsername: {{ .claimUsername | b64enc | quote }}
  {{- end }}
  {{- if .claimGroups }}
  claimGroups: {{ .claimGroups | b64enc | quote }}
  {{- end }}
  {{- if .usernamePrefix }}
  usernamePrefix: {{ .usernamePrefix | b64enc | quote }}
  {{- end }}
  {{- if .groupsPrefix }}
  groupsPrefix: {{ .groupsPrefix | b64enc | quote }}
  {{- end }}
  {{- if .customScopes }}
  customScopes: {{ .customScopes | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
